use std::cmp::Reverse;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use anstream::println;
use anyhow::{Context, Result};
use clap::{Args, Subcommand};
use jiff::{Timestamp, ToSpan};
use serde::{Deserialize, Serialize};

use crate::concurrency::run_concurrent;
use crate::config::AppConfig;
use crate::csvutil::{self, CsvRow};
use crate::lark::{LarkCli, append_hint, format_error_with_hint};
use crate::report::{write_csv, write_json};
use crate::util::{bytes_to_mb, format_bytes, timestamp_for_filename};
use fs_err as fs;

const DELETE_SUPPORTED_TYPES: &[&str] = &[
    "file", "docx", "bitable", "doc", "sheet", "mindnote", "folder", "shortcut", "slides",
];

#[derive(Debug, Args)]
pub struct DeleteCommand {
    #[command(subcommand)]
    command: DeleteSubcommand,
}

impl DeleteCommand {
    pub async fn run(self, config: &AppConfig) -> Result<()> {
        match self.command {
            DeleteSubcommand::Plan(command) => command.run(config).await,
            DeleteSubcommand::Apply(command) => command.run(config).await,
        }
    }
}

#[derive(Debug, Subcommand)]
enum DeleteSubcommand {
    /// Build a human-reviewable delete plan from list/audit CSV output.
    Plan(DeletePlanCommand),

    /// Delete only rows explicitly marked delete_candidate=true and human_confirmed=true.
    Apply(DeleteApplyCommand),
}

#[derive(Debug, Args)]
struct DeletePlanCommand {
    /// Input CSV from fst list/audit output.
    #[arg(long)]
    input: PathBuf,

    /// Mark rows as delete candidates when known size is at least this many MB.
    #[arg(long)]
    min_mb: Option<f64>,

    /// Keep only the largest N candidate rows. 0 means no top-N limit.
    #[arg(long)]
    top: Option<usize>,

    /// Inspect wiki rows and replace them with underlying Drive object type/token when possible.
    #[arg(long)]
    inspect_wiki: bool,

    /// Include rows with unknown size as non-candidate review rows.
    #[arg(long, num_args = 0..=1, default_missing_value = "true")]
    include_unknown: Option<bool>,

    /// Only keep rows whose last_open_time_iso is before this cutoff, e.g. 180d or 2024-01-01.
    #[arg(long)]
    opened_before: Option<String>,

    /// Only keep rows whose update_time_iso is before this cutoff, e.g. 180d or 2024-01-01.
    #[arg(long)]
    updated_before: Option<String>,

    /// Only keep rows whose create_time_iso is before this cutoff, e.g. 365d or 2023-01-01.
    #[arg(long)]
    created_before: Option<String>,
}

#[derive(Debug, Args)]
struct DeleteApplyCommand {
    /// Delete plan CSV generated by fst delete plan.
    #[arg(long)]
    input: PathBuf,

    /// Actually execute deletion. Without this flag, apply is a dry run.
    #[arg(long)]
    yes: bool,
}

#[derive(Debug, Clone)]
struct TimeFilters {
    opened_before: Option<Timestamp>,
    updated_before: Option<Timestamp>,
    created_before: Option<Timestamp>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct DeletePlanRow {
    delete_candidate: bool,
    human_confirmed: bool,
    title: String,
    doc_type: String,
    token: String,
    url: String,
    known_bytes: Option<u64>,
    known_mb: Option<f64>,
    size_source: String,
    size_confidence: String,
    reason: String,
    original_index: Option<usize>,
}

#[derive(Debug, Clone, Serialize)]
struct DeleteResultRow {
    title: String,
    doc_type: String,
    token: String,
    url: String,
    known_bytes: Option<u64>,
    known_mb: Option<f64>,
    status: String,
    dry_run: bool,
    error: Option<String>,
}

impl DeletePlanCommand {
    async fn run(self, config: &AppConfig) -> Result<()> {
        let min_mb = self.min_mb.unwrap_or(config.delete.min_mb);
        let top = self.top.unwrap_or(config.delete.top);
        let include_unknown = self
            .include_unknown
            .unwrap_or(config.delete.include_unknown);
        let time_filters = TimeFilters {
            opened_before: parse_cutoff_opt(self.opened_before.as_deref())?,
            updated_before: parse_cutoff_opt(self.updated_before.as_deref())?,
            created_before: parse_cutoff_opt(self.created_before.as_deref())?,
        };

        // First pass: parse rows that need no wiki inspection (cheap, sync),
        // and collect rows that DO need inspect into a separate list.
        let records = csvutil::read_csv_maps(&self.input)?;
        let mut rows = Vec::with_capacity(records.len());

        if self.inspect_wiki {
            let lark = Arc::new(LarkCli::new());
            let min_mb_inner = min_mb;
            let include_unknown_inner = include_unknown;
            let time_filters_inner = time_filters.clone();
            let inspected =
                run_concurrent(records, 8, None, None, None, move |_, record: CsvRow| {
                    let lark = lark.clone();
                    let time_filters_inner = time_filters_inner.clone();
                    async move {
                        plan_row_from_record(
                            record,
                            min_mb_inner,
                            include_unknown_inner,
                            &time_filters_inner,
                            Some(&*lark),
                        )
                        .await
                    }
                })
                .await;
            rows.extend(inspected.into_iter().flatten());
        } else {
            for record in records {
                if let Some(row) =
                    plan_row_from_record(record, min_mb, include_unknown, &time_filters, None).await
                {
                    rows.push(row);
                }
            }
        }

        rows.sort_by_key(|row| Reverse(row.known_bytes));

        if top > 0 {
            let mut candidate_seen = 0usize;
            for row in &mut rows {
                if row.delete_candidate {
                    candidate_seen += 1;
                    if candidate_seen > top {
                        row.delete_candidate = false;
                        row.reason = format!("outside top {} candidates", top);
                    }
                }
            }
        }

        let reports_dir = config.reports_dir();
        fs::create_dir_all(&reports_dir)?;
        let timestamp = timestamp_for_filename();
        let json_path = reports_dir.join(format!("delete-plan-{timestamp}.json"));
        let csv_path = reports_dir.join(format!("delete-plan-{timestamp}.csv"));
        write_json(&json_path, &rows)?;
        write_csv(&csv_path, &rows)?;

        let candidate_count = rows.iter().filter(|row| row.delete_candidate).count();
        let candidate_bytes: u64 = rows
            .iter()
            .filter(|row| row.delete_candidate)
            .map(|row| row.known_bytes.unwrap_or(0))
            .sum();
        println!("Delete plan written.");
        println!("Rows       : {}", rows.len());
        println!("Candidates : {}", candidate_count);
        println!("Known size : {}", format_bytes(candidate_bytes));
        println!("JSON       : {}", json_path.display());
        println!("CSV        : {}", csv_path.display());
        println!();
        println!("Review the CSV and set human_confirmed=true for rows you want to delete.");
        Ok(())
    }
}

impl DeleteApplyCommand {
    async fn run(self, config: &AppConfig) -> Result<()> {
        let rows = read_delete_plan(&self.input)?;
        let targets = rows
            .into_iter()
            .filter(|row| row.delete_candidate && row.human_confirmed)
            .collect::<Vec<_>>();

        if targets.is_empty() {
            println!("No rows have both delete_candidate=true and human_confirmed=true.");
            return Ok(());
        }

        let total_bytes: u64 = targets.iter().map(|row| row.known_bytes.unwrap_or(0)).sum();
        println!("Delete targets : {}", targets.len());
        println!("Known size     : {}", format_bytes(total_bytes));

        if !self.yes {
            println!("Dry run only. Re-run with --yes to execute lark-cli drive +delete --yes.");
        }

        let lark = LarkCli::new();
        let mut results = Vec::with_capacity(targets.len());

        for row in targets {
            let doc_type = normalize_delete_type(&row.doc_type);
            let mut status = if self.yes { "deleted" } else { "dry_run" }.to_string();
            let mut error = None;

            if row.token.trim().is_empty() {
                status = "skipped".to_string();
                error = Some("missing token".to_string());
            } else if !DELETE_SUPPORTED_TYPES.contains(&doc_type.as_str()) {
                status = "skipped".to_string();
                error = Some(format!("unsupported delete type: {}", row.doc_type));
            } else if self.yes {
                match lark
                    .run_with_retry([
                        "drive",
                        "+delete",
                        "--as",
                        "user",
                        "--file-token",
                        row.token.as_str(),
                        "--type",
                        doc_type.as_str(),
                        "--yes",
                    ])
                    .await
                {
                    Ok(output) if output.success => {}
                    Ok(output) => {
                        status = "failed".to_string();
                        error = Some(append_hint(output.combined.trim().to_string()));
                    }
                    Err(err) => {
                        status = "failed".to_string();
                        error = Some(format_error_with_hint(&err));
                    }
                }
            }

            results.push(DeleteResultRow {
                title: row.title,
                doc_type,
                token: row.token,
                url: row.url,
                known_bytes: row.known_bytes,
                known_mb: row.known_mb,
                status,
                dry_run: !self.yes,
                error,
            });
        }

        let reports_dir = config.reports_dir();
        fs::create_dir_all(&reports_dir)?;
        let timestamp = timestamp_for_filename();
        let json_path = reports_dir.join(format!("delete-results-{timestamp}.json"));
        let csv_path = reports_dir.join(format!("delete-results-{timestamp}.csv"));
        write_json(&json_path, &results)?;
        write_csv(&csv_path, &results)?;

        let failed = results.iter().filter(|row| row.status == "failed").count();
        let skipped = results.iter().filter(|row| row.status == "skipped").count();
        println!("Results JSON: {}", json_path.display());
        println!("Results CSV : {}", csv_path.display());
        println!("Failed      : {}", failed);
        println!("Skipped     : {}", skipped);
        Ok(())
    }
}

fn read_delete_plan(path: &Path) -> Result<Vec<DeletePlanRow>> {
    csvutil::read_csv_maps(path)?
        .into_iter()
        .map(delete_plan_row_from_csv)
        .collect()
}

fn delete_plan_row_from_csv(row: CsvRow) -> Result<DeletePlanRow> {
    Ok(DeletePlanRow {
        delete_candidate: csvutil::first_bool(&row, &["delete_candidate"]).unwrap_or(false),
        human_confirmed: csvutil::first_bool(&row, &["human_confirmed"]).unwrap_or(false),
        title: csvutil::get(&row, &["title"]),
        doc_type: csvutil::get(&row, &["doc_type", "type"]),
        token: csvutil::get(&row, &["token", "file_token"]),
        url: csvutil::get(&row, &["url"]),
        known_bytes: csvutil::first_known_size_bytes(&row),
        known_mb: csvutil::first_known_size_mb(&row),
        size_source: csvutil::get(&row, &["size_source"]),
        size_confidence: csvutil::get(&row, &["size_confidence"]),
        reason: csvutil::get(&row, &["reason"]),
        original_index: csvutil::first_u64(&row, &["original_index", "index"])
            .map(|value| value as usize),
    })
}

async fn plan_row_from_record(
    record: CsvRow,
    min_mb: f64,
    include_unknown: bool,
    time_filters: &TimeFilters,
    lark: Option<&LarkCli>,
) -> Option<DeletePlanRow> {
    let title = csvutil::get(&record, &["title"]);
    let mut doc_type =
        normalize_delete_type(&csvutil::get(&record, &["doc_type", "type", "entity_type"]));
    let mut token = csvutil::get(&record, &["token", "file_token"]);
    let url = csvutil::get(&record, &["url"]);
    if doc_type == "wiki"
        && let Some(lark) = lark
        && let Ok(Some((resolved_type, resolved_token))) =
            inspect_wiki_target(lark, &url, &token).await
    {
        doc_type = normalize_delete_type(&resolved_type);
        token = resolved_token;
    }
    if !passes_time_filters(&record, time_filters) {
        return None;
    }
    let known_bytes = csvutil::first_u64(
        &record,
        &[
            "total_bytes",
            "metadata_bytes",
            "export_bytes",
            "bytes",
            "known_bytes",
        ],
    );
    let known_mb = known_bytes.map(bytes_to_mb).or_else(|| {
        csvutil::first_f64(
            &record,
            &["total_mb", "metadata_mb", "export_mb", "mb", "known_mb"],
        )
    });
    let size_source = csvutil::get_or(
        &record,
        &["size_source"],
        if known_bytes.is_some() {
            "metadata"
        } else {
            "unknown"
        },
    );
    let size_confidence = csvutil::get_or(
        &record,
        &["size_confidence"],
        if known_bytes.is_some() {
            "known"
        } else {
            "unknown"
        },
    );
    let original_index =
        csvutil::first_u64(&record, &["index", "original_index"]).map(|value| value as usize);
    let is_supported = DELETE_SUPPORTED_TYPES.contains(&doc_type.as_str());
    let meets_threshold = known_mb.map(|mb| mb >= min_mb).unwrap_or(false);
    let delete_candidate = is_supported && meets_threshold;

    if known_bytes.is_none() && !include_unknown {
        return None;
    }

    Some(DeletePlanRow {
        delete_candidate,
        human_confirmed: false,
        title,
        doc_type,
        token,
        url,
        known_bytes,
        known_mb,
        size_source,
        size_confidence,
        reason: if !is_supported {
            "unsupported delete type".to_string()
        } else if delete_candidate {
            format!("known size >= {min_mb:.2} MB")
        } else if known_bytes.is_none() {
            "unknown size".to_string()
        } else {
            format!("known size < {min_mb:.2} MB")
        },
        original_index,
    })
}

fn passes_time_filters(record: &CsvRow, filters: &TimeFilters) -> bool {
    timestamp_before(
        record,
        &["last_open_time_iso", "opened_time_iso", "open_time_iso"],
        filters.opened_before,
    ) && timestamp_before(
        record,
        &["update_time_iso", "updated_time_iso", "modified_time_iso"],
        filters.updated_before,
    ) && timestamp_before(
        record,
        &["create_time_iso", "created_time_iso"],
        filters.created_before,
    )
}

fn timestamp_before(record: &CsvRow, keys: &[&str], cutoff: Option<Timestamp>) -> bool {
    let Some(cutoff) = cutoff else {
        return true;
    };
    let value = csvutil::get(record, keys);
    if value.trim().is_empty() {
        return false;
    }
    parse_timestamp(&value)
        .map(|timestamp| timestamp < cutoff)
        .unwrap_or(false)
}

fn parse_cutoff_opt(value: Option<&str>) -> Result<Option<Timestamp>> {
    value.map(parse_cutoff).transpose()
}

fn parse_cutoff(value: &str) -> Result<Timestamp> {
    let value = value.trim();
    // Try humantime-style relative duration first: "180d", "6months",
    // "12h", "2weeks 3days". Falls back to absolute date/datetime.
    if let Ok(duration) = humantime::parse_duration(value) {
        let secs = duration.as_secs();
        // humantime gives u64; jiff Timestamp subtraction wants i64.
        let secs = i64::try_from(secs).with_context(|| format!("duration too large: {value}"))?;
        return Ok(Timestamp::now() - secs.seconds());
    }
    parse_timestamp(value)
}

fn parse_timestamp(value: &str) -> Result<Timestamp> {
    let value = value.trim();
    if value.len() == 10 && value.as_bytes().get(4) == Some(&b'-') {
        return format!("{value}T00:00:00Z")
            .parse::<Timestamp>()
            .with_context(|| format!("parse date timestamp: {value}"));
    }
    value
        .parse::<Timestamp>()
        .or_else(|_| format!("{value}Z").parse::<Timestamp>())
        .with_context(|| format!("parse timestamp: {value}"))
}

async fn inspect_wiki_target(
    lark: &LarkCli,
    url: &str,
    token: &str,
) -> Result<Option<(String, String)>> {
    let target = if !url.trim().is_empty() { url } else { token };
    if target.trim().is_empty() {
        return Ok(None);
    }
    let obj = lark
        .json_with_retry([
            "drive", "+inspect", "--as", "user", "--url", target, "--format", "json",
        ])
        .await?;
    let data = obj.get("data").unwrap_or(&obj);
    let resolved_type = data
        .get("type")
        .or_else(|| data.get("obj_type"))
        .or_else(|| data.get("file_type"))
        .and_then(|value| value.as_str())
        .unwrap_or_default()
        .to_string();
    let resolved_token = data
        .get("token")
        .or_else(|| data.get("obj_token"))
        .or_else(|| data.get("file_token"))
        .and_then(|value| value.as_str())
        .unwrap_or_default()
        .to_string();
    if resolved_type.is_empty() || resolved_token.is_empty() {
        Ok(None)
    } else {
        Ok(Some((resolved_type, resolved_token)))
    }
}

fn normalize_delete_type(value: &str) -> String {
    match value.trim().to_ascii_lowercase().as_str() {
        "docx" => "docx".to_string(),
        "doc" => "doc".to_string(),
        "sheet" | "sheets" => "sheet".to_string(),
        "bitable" | "base" => "bitable".to_string(),
        "file" => "file".to_string(),
        "folder" => "folder".to_string(),
        "slides" | "slide" => "slides".to_string(),
        "shortcut" => "shortcut".to_string(),
        "mindnote" => "mindnote".to_string(),
        "wiki" => "wiki".to_string(),
        other => other.to_string(),
    }
}
